### ISSUE TITLE
JourneyMap 的路径点图标会被方块遮挡

### ISSUE THREAD

**Issue by LTCatt** [Hex-Dragon/ExploreOrigins#3]
![image](https://user-images.githubusercontent.com/40348278/119220530-900aba80-bb1d-11eb-9cc8-55ead1b97cb9.png)

**Comment by LTCatt** [comment]
与实体显示优化 Mod 无关，删除后 Bug 依然存在。
JourneyMap 的 GitHub Issue 上也没用这个问题……
@HerobrineXia 你看看你那有没有？

**Comment by HerobrineXia** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35889828/119221225-e9c0b400-bb20-11eb-9757-79325e6dca43.png">

**Comment by LTCatt** [comment]
已解决
